### PR TITLE
Update cake dependencies

### PR DESCRIPTION
**Pull request by derwasp**
I guess this is the same as #19, but bumping the version even further ;)
I also updated `paket.boostrapper.exe` because I had errors related to the new version of TLS.

### CODE REVIEW

**Comment by gep13** [comment]
@larzw do you have any idea why codecov is correctly posting to this PR?  I am a number of other projects where it isn't working, and it gets a 404 returned from the attempt.

**Comment by larzw** [comment]
@derwasp thanks a lot for the contribution!

@gep13 the only thing off the top of my head is your using a different version of codecov-exe. codecov-exe is having some issue right now. Maybe @stevepeak has a better idea?

**Comment by stevepeak** [comment]
Concerning this project: the issue is not obvious to me atm... ¯\_(ツ)_/¯

**Comment by aabenoja** [comment]
Out of curiosity what else is needed for this pr?

**Comment by jefflequeux** [comment]
Could you merge the pull request?

**Comment by Guymestef** [comment]
Since it's not yet merged... can we upgrade to Cake.Core 0.28.1?

**Comment by punker76** [comment]
@gep13 It would be nice to get this addin working together with Cake.Core 0.28.x (cause of #22 ) Thx

**Comment by gep13** [comment]
@punker76 I have just had a quick chat with @larzw the creator of this addin, and he is going to try to get a release out this weekend.  If that doesn't happen, I will arrange a call with him to walk through the process of the release, and get something out early next week.

**Comment by punker76** [comment]
@gep13 sounds great!

**Comment by batzen** [comment]
This PR updates cake to 0.26. Would be nice if it could be updated to 0.29 ;-)

**Comment by larzw** [comment]
Thanks you everyone for your patience! Version 3.0.0 of this addin contains @derwasp PR (updating to cake 0.26.0) while version 4.0.0 closes #22 (updating to cake 0.28.1). On another note, is there anyone that would be interested in taking over the maintenance of this addin and module? If so, please see issue #25 for discussion. Thanks!

**Comment by gep13** [comment]
@punker76 can you take the latest version for a spin and see how you get on?

**Comment by punker76** [comment]
@gep13 Works great! Thx @larzw

**Pull request merged**
